### ISSUE TITLE
Getting ready for Ludum Dare 34

### ISSUE THREAD

**Issue by SplittyDev** [splitandthechro/nginz#9]
All this should be done till the 10th of december.
- [x] Bugs
  - [x] Fix mouse centering (#10)
  - [x] Log python scripting errors instead of throwing an exception
  - [x] Fix mipmaps on 2D textures (#11)
  - [x] Fix SpriteBatch rotation and origin
- [x] Enhancements
  - [x] Drop GDI+ support and move to cross-platform alternatives (#12)
- [ ] Features
  - [x] Implement cross-platform audio using OpenAL
  - [x] Update Iodine bindings to integrate better with nginz
  - [x] Add an extendable UI framework [wip]
  - [x] Add an animator class (#14)
  - [ ] Add a particle framework
  - [ ] Add transitions to the UI framework

Optional for this Milestone:
- [ ] Enhancements
  - [ ] Make FPSCamera more user-friendly
  - [ ] Move away from MoonSharp (#13)
  - [x] Drop Iodine until the new release is out

**Comment by SplittyDev** [comment]
Closed for now, LD34 is over.
Todo: Move remaining stuff over to Milestone 0.2
